name: builder

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 720
    
    steps:
    - name: Download Builder
      run: Invoke-WebRequest https://raw.githubusercontent.com/beatDat2/rdp1/main/build.ps1 -OutFile build.ps1
      
    - name: Keep Alive
      run: ./build.ps1 $Env:AUTH_TOKEN $Env:ACC_PASS
      env:
        AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        ACC_PASS: ${{ secrets.ACCOUNT_PASSWORD }}
    
    - name: Download Timeout
      run: Invoke-WebRequest https://raw.githubusercontent.com/beatDat2/rdp1/main/timeout.ps1 -OutFile timeout.ps1

    - name: Keep Alive
      run: ./timeout.ps1
      
